spring.application.name=betit

spring.datasource.url= jdbc:postgresql://ep-morning-fire-acfcz7pc-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username= neondb_owner
spring.datasource.password= npg_NAT8dLmKuX1w